### ISSUE TITLE
file_stream only works on things with getvalue()

### ISSUE THREAD

**Issue by dracos** [pyexcel/pyexcel-xls#16]
Using `file_stream` works fine with a CSV file, but dies with an XLS file:
```
>>> import pyexcel
>>> pyexcel.get_records(file_stream=open('foo.csv'), file_type='csv')[0]
{u'A': 1, u'C': 3, u'B': 2, u'E': '', u'D': ''}
>>> pyexcel.get_records(file_stream=open('foo.xls'), file_type='xls')[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python2.7/site-packages/pyexcel/core.py", line 330, in get_records
    **keywords)
  File ".../lib/python2.7/site-packages/pyexcel/core.py", line 67, in get_sheet
    named_content = sources.get_sheet_stream(**keywords)
  File ".../lib/python2.7/site-packages/pyexcel/sources/__init__.py", line 15, in get_sheet_stream
    sheets = source.get_data()
  File ".../lib/python2.7/site-packages/pyexcel/sources/file_source_input.py", line 83, in get_data
    **self.__keywords)
  File ".../lib/python2.7/site-packages/pyexcel_io/io.py", line 38, in get_data
    file_type=file_type, **keywords)
  File ".../lib/python2.7/site-packages/pyexcel_io/io.py", line 148, in load_data
    result = reader.read_all()
  File ".../lib/python2.7/site-packages/pyexcel_xls/xls.py", line 113, in read_all
    self._native_book = self._get_book()
  File ".../lib/python2.7/site-packages/pyexcel_xls/xls.py", line 131, in _get_book
    file_contents=self._file_stream.getvalue(),
AttributeError: 'file' object has no attribute 'getvalue'
```
It looks like the line at https://github.com/pyexcel/pyexcel-xls/blob/771969ec849447440c96b81761c77d47bcd406cb/pyexcel_xls/xls.py#L131 means that only streams that have `getvalue()` (e.g. StringIO) can be used. Could this be extended to work with any file-type object? (I realise in this case I could call read() and pass that to `file_content` but I came across this with a different file-type object.)

**Comment by chfw** [comment]
please use pyexcel-xls 0.3.2
