### ISSUE TITLE
Cannot read from url: AttributeError: addinfourl instance has no attribute 'seek'

### ISSUE THREAD

**Issue by dimasfs** [pyexcel/pyexcel-xls#20]
Hello there,

I am trying to read a book using get_book and get following error message:

```
Python 2.7.13 (default, Aug 22 2017, 13:19:02)
[GCC 4.8.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyexcel
>>> book = pyexcel.get_book(url='http://server/filename.xlsx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python2.7/lib/python2.7/site-packages/pyexcel/core.py", line 46, in get_book
    book_stream = sources.get_book_stream(**keywords)
  File "/opt/python2.7/lib/python2.7/site-packages/pyexcel/internal/core.py", line 33, in get_book_stream
    sheets = a_source.get_data()
  File "/opt/python2.7/lib/python2.7/site-packages/pyexcel/plugins/sources/http.py", line 58, in get_data
    **self._keywords)
  File "/opt/python2.7/lib/python2.7/site-packages/pyexcel/plugins/parsers/excel.py", line 21, in parse_file_stream
    file_stream, file_type=self._file_type, **keywords)
  File "/opt/python2.7/lib/python2.7/site-packages/pyexcel/plugins/parsers/excel.py", line 35, in _parse_any
    anything, file_type=file_type, **keywords)
  File "/opt/python2.7/lib/python2.7/site-packages/pyexcel_io/io.py", line 65, in get_data
    streaming=False, **keywords)
  File "/opt/python2.7/lib/python2.7/site-packages/pyexcel_io/io.py", line 83, in _get_data
    return load_data(**keywords)
  File "/opt/python2.7/lib/python2.7/site-packages/pyexcel_io/io.py", line 187, in load_data
    result = reader.read_all()
  File "/opt/python2.7/lib/python2.7/site-packages/pyexcel_xls/xlsr.py", line 109, in read_all
    self._native_book = self._get_book()
  File "/opt/python2.7/lib/python2.7/site-packages/pyexcel_xls/xlsr.py", line 128, in _get_book
    self._file_stream.seek(0)
AttributeError: addinfourl instance has no attribute 'seek'
```

If the line "self._file_stream.seek(0)" is removed, then it works.

Would someone please take a look at it?

Best regards,
D

**Comment by chfw** [comment]
Looking at it.

**Comment by chfw** [comment]
reproduced and will fix.

**Comment by dimasfs** [comment]
Hello There,

thank you very much. It works!

**Comment by chfw** [comment]
@dimasfs thanks for your prompt verification. Will get it out of the door quickly.
