### ISSUE TITLE
Tests use 'mock' on Python3

### ISSUE THREAD

**Issue by jayvdb** [pyexcel/pyexcel-xls#29]
Backport 'mock' shouldnt be used on Python 3.

```
[   52s] ======================================================================
[   52s] ERROR: Failure: ModuleNotFoundError (No module named 'mock')
[   52s] ----------------------------------------------------------------------
[   52s] Traceback (most recent call last):
[   52s]   File "/usr/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
[   52s]     raise self.exc_val.with_traceback(self.tb)
[   52s]   File "/usr/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
[   52s]     addr.filename, addr.module)
[   52s]   File "/usr/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
[   52s]     return self.importFromDir(dir_path, fqname)
[   52s]   File "/usr/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
[   52s]     mod = load_module(part_fqname, fh, filename, desc)
[   52s]   File "/usr/lib64/python3.7/imp.py", line 234, in load_module
[   52s]     return load_source(name, filename, file)
[   52s]   File "/usr/lib64/python3.7/imp.py", line 171, in load_source
[   52s]     module = _load(spec)
[   52s]   File "<frozen importlib._bootstrap>", line 696, in _load
[   52s]   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
[   52s]   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
[   52s]   File "<frozen importli[   52s] ======================================================================
[   52s] ERROR: Failure: ModuleNotFoundError (No module named 'mock')
[   52s] ----------------------------------------------------------------------
[   52s] Traceback (most recent call last):
[   52s]   File "/usr/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
[   52s]     raise self.exc_val.with_traceback(self.tb)
[   52s]   File "/usr/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
[   52s]     addr.filename, addr.module)
[   52s]   File "/usr/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
[   52s]     return self.importFromDir(dir_path, fqname)
[   52s]   File "/usr/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
[   52s]     mod = load_module(part_fqname, fh, filename, desc)
[   52s]   File "/usr/lib64/python3.7/imp.py", line 234, in load_module
[   52s]     return load_source(name, filename, file)
[   52s]   File "/usr/lib64/python3.7/imp.py", line 171, in load_source
[   52s]     module = _load(spec)
[   52s]   File "<frozen importlib._bootstrap>", line 696, in _load
[   52s]   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
[   52s]   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
[   52s]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[   52s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-xls-0.5.8/tests/test_bug_fixes.py", line 16, in <module>
[   52s]     from mock import patch
[   52s] ModuleNotFoundError: No module named 'mock'
b._bootstrap>", line 219, in _call_with_frames_removed
[   52s]   File "/home/abuild/rpmbuild/BUILD/pyexcel-xls-0.5.8/tests/test_bug_fixes.py", line 16, in <module>
[   52s]     from mock import patch
[   52s] ModuleNotFoundError: No module named 'mock'
```

**Comment by jayvdb** [comment]
Also in `pyexcel` core's tests, xlsx, and probably many other plugins.

**Comment by chfw** [comment]
yep, this library has remove python 2.7's mock for next release.
